### ISSUE TITLE
Badge commit fails

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-timings#5]
```
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_BRANCH value: 
M	README.md
INPUT_FILE_PATTERN: .
INPUT_COMMIT_OPTIONS: 
[detached HEAD 27cc9a7] Updated badges
 Author: renovate[bot] <renovate[bot]@users.noreply.github.com>
 1 file changed, 1 insertion(+), 1 deletion(-)
INPUT_TAGGING_MESSAGE: 
No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: 
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
```

**Comment by bahmutov** [comment]
Now the error has changed to
```
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_BRANCH value: main
Switched to a new branch 'main'
M	README.md
Branch 'main' set up to track remote branch 'main' from 'origin'.
INPUT_FILE_PATTERN: README.md
INPUT_COMMIT_OPTIONS: 
[main d81b8a3] Updated badges
 Author: bahmutov <bahmutov@users.noreply.github.com>
 1 file changed, 1 insertion(+), 1 deletion(-)
INPUT_TAGGING_MESSAGE: 
No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: 
fatal: could not read Username for 'github.com': No such device or address
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
```

**Comment by bahmutov** [comment]
done https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
